mongo:
  config:
    connection_string: "mongodb://localhost:27017"
    db_name: "Coupons"
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) %logger{36} - %clr(%msg){magenta}%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: couponsProject.log
    path: log/
    max-size: 10MB
    max-history: 3
jwt:
  secret: "daniel"
server:
  port: 8080
